
name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.34.0
        toolchain: stable

    - name: Check Global Loader
      run: cargo check --verbose --features=global_loader
      
    - name: Check Struct Loader
      run: cargo check --verbose --features=struct_loader
      
    - name: Tests With All Features
      run: cargo test --all-features
