
name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set Rust Version
      run: rustup default 1.34.0
      
    - name: Display Versions
      run: cargo --version && rustc --version

    - name: Check Global Loader
      run: cargo check --verbose --features=global_loader
      
    - name: Check Struct Loader
      run: cargo check --verbose --features=struct_loader
      
    - name: Tests With All Features
      run: cargo test --all-features
